const PRODUCTS = [
  {
    id: "torpedo-bronce-alpaca",
    name: "Torpedo Bronce y Alpaca",
    subtitle: "Virola cincelada + bombilla",
    description: "Mate torpedo de cuero con pelotitas de bronce y virola cincelada de alpaca. Incluye bombilla de acero inoxidable. Una pieza de lujo para verdaderos materos.",
    price: 50000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/torpedo-bronce-alpaca.jpg",
    materials: ["Cuero", "Alpaca", "Bronce", "Calabaza"],
    features: ["Virola cincelada a mano", "Base reforzada", "Incluye bombilla de acero"],
    care: "Curar antes de usar. Secar con papel absorbente después de cada uso y dejar en lugar ventilado.",
    rating: 5.0,
    reviews: 24,
    featured: true,
    onSale: false
  },
  {
    id: "torpedo-cuero-croco",
    name: "Torpedo Cuero Croco",
    subtitle: "Premium con pelota de bronce",
    description: "Mate torpedo forrado en cuero textura croco premium con detalle de pelota de bronce. Incluye bombilla de acero.",
    price: 42000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/torpedo-cuero-croco.jpg",
    materials: ["Cuero Croco", "Bronce", "Calabaza"],
    features: ["Textura premium", "Virola de acero", "Incluye bombilla"],
    care: "Curar antes de usar. Secar bien el interior.",
    rating: 4.8,
    reviews: 15,
    featured: true,
    onSale: false
  },
  {
    id: "mate-imperial-acero",
    name: "Mate Imperial Acero",
    subtitle: "Interior acero inoxidable",
    description: "Mate Imperial con interior de acero inoxidable térmico. No requiere curado, fácil de limpiar y mantiene la temperatura. Incluye bombilla.",
    price: 40000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-imperial-acero.jpg",
    materials: ["Acero Inoxidable", "Cuero", "Alpaca"],
    features: ["Interior térmico", "No necesita curado", "Virola cincelada", "Incluye bombilla"],
    care: "Lavar con agua tibia. No usar esponjas abrasivas en el exterior.",
    rating: 4.9,
    reviews: 32,
    featured: true,
    onSale: false
  },
  {
    id: "termo-argentina-360",
    name: "Termo Argentina 360º",
    subtitle: "1L Negro media manija",
    description: "Termo de acero inoxidable color negro mate con diseño exclusivo de Argentina. Sistema 360º y media manija.",
    price: 35000,
    originalPrice: null,
    category: "Termos",
    categorySlug: "termos",
    image: "assets/images/products/termo-argentina-360.jpg",
    materials: ["Acero Inoxidable", "Plástico Libre de BPA"],
    features: ["Capacidad 1 Litro", "Conserva calor por 24hs", "Pico cebador 360º"],
    care: "Lavar con agua tibia y jabón neutro. No usar lavavajillas.",
    rating: 5.0,
    reviews: 41,
    featured: true,
    onSale: false
  },
  {
    id: "termo-system-1l",
    name: "Termo System 1L",
    subtitle: "Negro con tapamate",
    description: "Termo negro de 1 Litro con manija lateral y tapa que funciona como mate. Práctico e ideal para viajes.",
    price: 40000,
    originalPrice: null,
    category: "Termos",
    categorySlug: "termos",
    image: "assets/images/products/termo-system-1l.jpg",
    materials: ["Acero Inoxidable"],
    features: ["Tapa funcional como mate", "Doble pared al vacío", "Manija ergonómica"],
    care: "Lavar a mano. Dejar destapado cuando no se usa.",
    rating: 4.7,
    reviews: 18,
    featured: true,
    onSale: false
  },
  {
    id: "termo-media-manija",
    name: "Termo Media Manija",
    subtitle: "Negro 1L",
    description: "Termo clásico de acero inoxidable en color negro con media manija. Pico cebador de precisión.",
    price: 22000,
    originalPrice: null,
    category: "Termos",
    categorySlug: "termos",
    image: "assets/images/products/termo-media-manija.jpg",
    materials: ["Acero Inoxidable"],
    features: ["Excelente retención de calor", "Pico de precisión"],
    care: "Lavar a mano.",
    rating: 4.6,
    reviews: 29,
    featured: false,
    onSale: false
  },
  {
    id: "canasta-cuero-grande",
    name: "Canasta 100% Cuero",
    subtitle: "Grande y reforzada",
    description: "Canasta matera elaborada en 100% cuero vacuno negro. Costuras reforzadas, ideal para transportar termo de 1L, mate y latas.",
    price: 35000,
    originalPrice: null,
    category: "Canastas",
    categorySlug: "canastas",
    image: "assets/images/products/canasta-cuero-grande.jpg",
    materials: ["Cuero Vacuno"],
    features: ["Costuras reforzadas a mano", "Base rígida", "Capacidad para termo de 1.5L"],
    care: "Limpiar con paño húmedo. Hidratar el cuero ocasionalmente.",
    rating: 4.9,
    reviews: 11,
    featured: true,
    onSale: false
  },
  {
    id: "canasta-matera-alta",
    name: "Canasta Matera Alta",
    subtitle: "Con detalles grabados",
    description: "Matera alta de cuero marrón con detalles grabados y costuras artesanales. Diseño elegante y resistente.",
    price: 29500,
    originalPrice: null,
    category: "Canastas",
    categorySlug: "canastas",
    image: "assets/images/products/canasta-matera-alta.jpg",
    materials: ["Cuero Vacuno"],
    features: ["Diseño vertical", "Detalles bajo relieve", "Correa resistente"],
    care: "Limpiar con paño húmedo.",
    rating: 4.8,
    reviews: 14,
    featured: false,
    onSale: false
  },
  {
    id: "bombillon-alpaca",
    name: "Bombillón Premium",
    subtitle: "100% alpaca, pico loro",
    description: "Bombillón artesanal fabricado íntegramente en alpaca con diseño pico de loro. No se tapa y enfría el agua antes de llegar a la boca.",
    price: 21000,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/bombillon-alpaca.jpg",
    materials: ["Alpaca 100%"],
    features: ["Pico de loro ancho", "Filtro tipo pala", "Soldadura de plata"],
    care: "Hervir en agua con bicarbonato de sodio una vez al mes para limpieza profunda.",
    rating: 5.0,
    reviews: 56,
    featured: true,
    onSale: false
  },
  {
    id: "latas-forradas-x2",
    name: "Latas Forradas x2",
    subtitle: "Yerbero + Azucarero",
    description: "Juego de dos latas (yerbero con pico vertedor y azucarero) forradas en eco-cuero negro con detalles de costura.",
    price: 12000,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/latas-forradas-x2.jpg",
    materials: ["Hojalata", "Eco-cuero"],
    features: ["Pico vertedor plástico", "Forradas a mano", "Base de acero"],
    care: "No sumergir en agua. Limpiar con paño seco.",
    rating: 4.5,
    reviews: 22,
    featured: false,
    onSale: false
  },
  {
    id: "chau-lata-x2",
    name: "Chau Lata x2",
    subtitle: "Yerbero + Azucarero",
    description: "Set de yerbero y azucarero tipo 'chau lata' de cuero negro con cierre reforzado. Práctico y ocupa menos espacio.",
    price: 13500,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/chau-lata-x2.jpg",
    materials: ["Cuero", "Tela impermeable"],
    features: ["Interior impermeable", "Cierres YKK reforzados", "Adaptable al espacio"],
    care: "Lavar interior con paño húmedo.",
    rating: 4.7,
    reviews: 38,
    featured: false,
    onSale: false
  },
  {
    id: "mate-camionero-algarrobo",
    name: "Mate Camionero Algarrobo",
    subtitle: "Madera noble forrada en cuero",
    description: "Mate camionero de algarrobo macizo, forrado en cuero de exportación con costuras reforzadas a mano. Virola de acero inoxidable.",
    price: 32000,
    originalPrice: 38000,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/camionero-algarrobo.jpg",
    materials: ["Madera", "Cuero", "Alpaca"],
    features: ["Madera noble aromática", "Costura reforzada", "Excelente agarre"],
    care: "Curar con yerba húmeda por 24hs. No dejar con agua.",
    rating: 4.9,
    reviews: 17,
    featured: false,
    onSale: true
  },
  {
    id: "mate-camionero-premium",
    name: "Mate Camionero Premium",
    subtitle: "Calabaza forrada en cuero",
    description: "El clásico mate camionero uruguayo. Calabaza seleccionada de paredes gruesas, forrado en cuero vacuno grueso con virola cincelada.",
    price: 45000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/camionero-premium.jpg",
    materials: ["Calabaza", "Cuero", "Alpaca"],
    features: ["Calabaza seleccionada", "Cuero vacuno genuino", "Virola cincelada"],
    care: "Curar bien antes de usar para evitar hongos.",
    rating: 4.8,
    reviews: 21,
    featured: true,
    onSale: false
  },
  {
    id: "mate-camionero-acero",
    name: "Mate Camionero Térmico",
    subtitle: "Acero inoxidable y cuero",
    description: "Mate camionero moderno con interior de acero inoxidable térmico de doble pared, forrado en cuero vacuno negro con virola de alpaca.",
    price: 39000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/camionero-acero.jpg",
    materials: ["Acero Inoxidable", "Cuero"],
    features: ["Interior de acero térmico", "Fácil lavado", "No necesita curado"],
    care: "Lavar interior con agua tibia.",
    rating: 4.7,
    reviews: 9,
    featured: false,
    onSale: false
  },
  {
    id: "mate-tradicional-calabaza",
    name: "Mate Tradicional Calabaza",
    subtitle: "Calabaza natural y soporte de cuero",
    description: "Mate tradicional elaborado a partir de calabaza natural pulida, con soporte o pie de cuero vacuno para una perfecta estabilidad.",
    price: 24000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/tradicional-calabaza.jpg",
    materials: ["Calabaza", "Cuero"],
    features: ["Calabaza 100% natural", "Pie de cuero estable", "Sabor clásico"],
    care: "Curar antes de usar. Secar siempre boca arriba.",
    rating: 4.6,
    reviews: 13,
    featured: false,
    onSale: false
  }
];

// Helper to filter/sort
const getProductsByCategory = (slug) => PRODUCTS.filter(p => p.categorySlug === slug);
const getProductById = (id) => PRODUCTS.find(p => p.id === id);
const getFeaturedProducts = () => PRODUCTS.filter(p => p.featured);

const getProductsByMaterial = (material) => PRODUCTS.filter(p => 
  p.materials.some(m => m.toLowerCase().includes(material.toLowerCase()))
);

const getProductsByType = (type) => PRODUCTS.filter(p => {
  const t = type.toLowerCase();
  return p.name.toLowerCase().includes(t) || 
         p.subtitle.toLowerCase().includes(t) || 
         (p.id && p.id.includes(t));
});

const sortProducts = (products, type) => {
  switch (type) {
    case 'price-asc': return [...products].sort((a, b) => a.price - b.price);
    case 'price-desc': return [...products].sort((a, b) => b.price - a.price);
    case 'rating': return [...products].sort((a, b) => b.rating - a.rating);
    case 'featured': default: return [...products].sort((a, b) => (b.featured ? 1 : -1));
  }
};
