const PRODUCTS = [
  {
    id: "torpedo-bronce-alpaca",
    name: "Torpedo Bronce y Alpaca",
    subtitle: "Virola cincelada + bombilla",
    description: "Mate torpedo de cuero con pelotitas de bronce y virola cincelada de alpaca. Incluye bombilla de acero inoxidable. Una pieza de lujo para verdaderos materos.",
    price: 50000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/torpedo-bronce-alpaca.jpg",
    materials: ["Cuero", "Alpaca", "Bronce", "Calabaza"],
    features: ["Virola cincelada a mano", "Base reforzada", "Incluye bombilla de acero"],
    care: "Curar antes de usar. Secar con papel absorbente después de cada uso y dejar en lugar ventilado.",
    rating: 5.0,
    reviews: 24,
    featured: true,
    onSale: false
  },
  {
    id: "torpedo-cuero-croco",
    name: "Torpedo Cuero Croco",
    subtitle: "Premium con pelota de bronce",
    description: "Mate torpedo forrado en cuero textura croco premium con detalle de pelota de bronce. Incluye bombilla de acero.",
    price: 42000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/torpedo-cuero-croco.jpg",
    materials: ["Cuero Croco", "Bronce", "Calabaza"],
    features: ["Textura premium", "Virola de acero", "Incluye bombilla"],
    care: "Curar antes de usar. Secar bien el interior.",
    rating: 4.8,
    reviews: 15,
    featured: true,
    onSale: false
  },
  {
    id: "mate-imperial-acero",
    name: "Mate Imperial Acero",
    subtitle: "Interior acero inoxidable",
    description: "Mate Imperial con interior de acero inoxidable térmico. No requiere curado, fácil de limpiar y mantiene la temperatura. Incluye bombilla.",
    price: 40000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-imperial-acero.jpg",
    materials: ["Acero Inoxidable", "Cuero", "Alpaca"],
    features: ["Interior térmico", "No necesita curado", "Virola cincelada", "Incluye bombilla"],
    care: "Lavar con agua tibia. No usar esponjas abrasivas en el exterior.",
    rating: 4.9,
    reviews: 32,
    featured: true,
    onSale: false
  },
  {
    id: "termo-argentina-360",
    name: "Termo Argentina 360º",
    subtitle: "1L Negro media manija",
    description: "Termo de acero inoxidable color negro mate con diseño exclusivo de Argentina. Sistema 360º y media manija.",
    price: 35000,
    originalPrice: null,
    category: "Termos",
    categorySlug: "termos",
    image: "assets/images/products/termo-argentina-360.jpg",
    materials: ["Acero Inoxidable", "Plástico Libre de BPA"],
    features: ["Capacidad 1 Litro", "Conserva calor por 24hs", "Pico cebador 360º"],
    care: "Lavar con agua tibia y jabón neutro. No usar lavavajillas.",
    rating: 5.0,
    reviews: 41,
    featured: true,
    onSale: false
  },
  {
    id: "termo-system-1l",
    name: "Termo System 1L",
    subtitle: "Negro con tapamate",
    description: "Termo negro de 1 Litro con manija lateral y tapa que funciona como mate. Práctico e ideal para viajes.",
    price: 40000,
    originalPrice: null,
    category: "Termos",
    categorySlug: "termos",
    image: "assets/images/products/termo-system-1l.jpg",
    materials: ["Acero Inoxidable"],
    features: ["Tapa funcional como mate", "Doble pared al vacío", "Manija ergonómica"],
    care: "Lavar a mano. Dejar destapado cuando no se usa.",
    rating: 4.7,
    reviews: 18,
    featured: true,
    onSale: false
  },
  {
    id: "termo-media-manija",
    name: "Termo Media Manija",
    subtitle: "Negro 1L",
    description: "Termo clásico de acero inoxidable en color negro con media manija. Pico cebador de precisión.",
    price: 22000,
    originalPrice: null,
    category: "Termos",
    categorySlug: "termos",
    image: "assets/images/products/termo-media-manija.jpg",
    materials: ["Acero Inoxidable"],
    features: ["Excelente retención de calor", "Pico de precisión"],
    care: "Lavar a mano.",
    rating: 4.6,
    reviews: 29,
    featured: false,
    onSale: false
  },
  {
    id: "canasta-cuero-grande",
    name: "Canasta 100% Cuero",
    subtitle: "Grande y reforzada",
    description: "Canasta matera elaborada en 100% cuero vacuno negro. Costuras reforzadas, ideal para transportar termo de 1L, mate y latas.",
    price: 35000,
    originalPrice: null,
    category: "Canastas",
    categorySlug: "canastas",
    image: "assets/images/products/canasta-cuero-grande.jpg",
    materials: ["Cuero Vacuno"],
    features: ["Costuras reforzadas a mano", "Base rígida", "Capacidad para termo de 1.5L"],
    care: "Limpiar con paño húmedo. Hidratar el cuero ocasionalmente.",
    rating: 4.9,
    reviews: 11,
    featured: true,
    onSale: false
  },
  {
    id: "canasta-matera-alta",
    name: "Canasta Matera Alta",
    subtitle: "Con detalles grabados",
    description: "Matera alta de cuero marrón con detalles grabados y costuras artesanales. Diseño elegante y resistente.",
    price: 29500,
    originalPrice: null,
    category: "Canastas",
    categorySlug: "canastas",
    image: "assets/images/products/canasta-matera-alta.jpg",
    materials: ["Cuero Vacuno"],
    features: ["Diseño vertical", "Detalles bajo relieve", "Correa resistente"],
    care: "Limpiar con paño húmedo.",
    rating: 4.8,
    reviews: 14,
    featured: false,
    onSale: false
  },
  {
    id: "bombillon-alpaca",
    name: "Bombillón Premium",
    subtitle: "100% alpaca, pico loro",
    description: "Bombillón artesanal fabricado íntegramente en alpaca con diseño pico de loro. No se tapa y enfría el agua antes de llegar a la boca.",
    price: 21000,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/bombillon-alpaca.jpg",
    materials: ["Alpaca 100%"],
    features: ["Pico de loro ancho", "Filtro tipo pala", "Soldadura de plata"],
    care: "Hervir en agua con bicarbonato de sodio una vez al mes para limpieza profunda.",
    rating: 5.0,
    reviews: 56,
    featured: true,
    onSale: false
  },
  {
    id: "latas-forradas-x2",
    name: "Latas Forradas x2",
    subtitle: "Yerbero + Azucarero",
    description: "Juego de dos latas (yerbero con pico vertedor y azucarero) forradas en eco-cuero negro con detalles de costura.",
    price: 12000,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/latas-forradas-x2.png",
    materials: ["Hojalata", "Eco-cuero"],
    features: ["Pico vertedor plástico", "Forradas a mano", "Base de acero"],
    care: "No sumergir en agua. Limpiar con paño seco.",
    rating: 4.5,
    reviews: 22,
    featured: false,
    onSale: false
  },
  {
    id: "chau-lata-x2",
    name: "Chau Lata x2",
    subtitle: "Yerbero + Azucarero",
    description: "Set de yerbero y azucarero tipo 'chau lata' de cuero negro con cierre reforzado. Práctico y ocupa menos espacio.",
    price: 13500,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/chau-lata-x2.jpg",
    materials: ["Cuero", "Tela impermeable"],
    features: ["Interior impermeable", "Cierres YKK reforzados", "Adaptable al espacio"],
    care: "Lavar interior con paño húmedo.",
    rating: 4.7,
    reviews: 38,
    featured: false,
    onSale: false
  },
  {
    id: "mate-camionero-algarrobo",
    name: "Mate Camionero Algarrobo",
    subtitle: "Madera noble forrada en cuero",
    description: "Mate camionero de algarrobo macizo, forrado en cuero de exportación con costuras reforzadas a mano. Virola de acero inoxidable.",
    price: 32000,
    originalPrice: 38000,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/camionero-algarrobo.jpg",
    materials: ["Madera", "Cuero", "Alpaca"],
    features: ["Madera noble aromática", "Costura reforzada", "Excelente agarre"],
    care: "Curar con yerba húmeda por 24hs. No dejar con agua.",
    rating: 4.9,
    reviews: 17,
    featured: false,
    onSale: true
  },
  {
    id: "mate-camionero-premium",
    name: "Mate Camionero Premium",
    subtitle: "Calabaza forrada en cuero",
    description: "El clásico mate camionero uruguayo. Calabaza seleccionada de paredes gruesas, forrado en cuero vacuno grueso con virola cincelada.",
    price: 45000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/camionero-premium.jpg",
    materials: ["Calabaza", "Cuero", "Alpaca"],
    features: ["Calabaza seleccionada", "Cuero vacuno genuino", "Virola cincelada"],
    care: "Curar bien antes de usar para evitar hongos.",
    rating: 4.8,
    reviews: 21,
    featured: true,
    onSale: false
  },
  {
    id: "mate-camionero-acero",
    name: "Mate Camionero Térmico",
    subtitle: "Acero inoxidable y cuero",
    description: "Mate camionero moderno con interior de acero inoxidable térmico de doble pared, forrado en cuero vacuno negro con virola de alpaca.",
    price: 39000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/camionero-acero.jpg",
    materials: ["Acero Inoxidable", "Cuero"],
    features: ["Interior de acero térmico", "Fácil lavado", "No necesita curado"],
    care: "Lavar interior con agua tibia.",
    rating: 4.7,
    reviews: 9,
    featured: false,
    onSale: false
  },
  {
    id: "mate-tradicional-calabaza",
    name: "Mate Tradicional Calabaza",
    subtitle: "Calabaza natural y soporte de cuero",
    description: "Mate tradicional elaborado a partir de calabaza natural pulida, con soporte o pie de cuero vacuno para una perfecta estabilidad.",
    price: 24000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/tradicional-calabaza.jpg",
    materials: ["Calabaza", "Cuero"],
    features: ["Calabaza 100% natural", "Pie de cuero estable", "Sabor clásico"],
    care: "Curar antes de usar. Secar siempre boca arriba.",
    rating: 4.6,
    reviews: 13,
    featured: false,
    onSale: false
  },
  {
    id: "mate-torpedo-estuche",
    name: "Mate Torpedo Premium con Estuche",
    subtitle: "Cuero seleccionado + estuche de raso",
    description: "Espacio para descripción personalizada. Mate torpedo forrado en cuero legítimo con virola de alpaca cincelada a mano, presentado en estuche de raso satinado.",
    price: 49000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-torpedo-estuche.png",
    materials: ["Cuero", "Alpaca", "Calabaza"],
    features: ["Estuche de raso premium", "Virola cincelada", "Calabaza gruesa"],
    care: "Curar antes de usar. Secar bien.",
    rating: 4.9,
    reviews: 12,
    featured: true,
    onSale: false
  },
  {
    id: "mate-torpedo-labrado",
    name: "Mate Torpedo Labrado Rústico",
    subtitle: "Cuero marrón labrado y virola de bronce",
    description: "Espacio para descripción personalizada. Mate torpedo forrado en cuero labrado de color marrón rústico con virola de bronce cincelada.",
    price: 43000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-torpedo-labrado.png",
    materials: ["Cuero", "Bronce", "Calabaza"],
    features: ["Cuero labrado a mano", "Virola de bronce", "Estilo rústico"],
    care: "Curar antes de usar. Limpiar con paño seco el exterior.",
    rating: 4.8,
    reviews: 8,
    featured: false,
    onSale: false
  },
  {
    id: "mate-imperial-pie",
    name: "Mate Imperial de Pie con Patas",
    subtitle: "Base cincelada y patas de bronce",
    description: "Espacio para descripción personalizada. Mate imperial con soporte de 4 patas cinceladas de bronce. Forrado en cuero premium con virola cincelada de alpaca.",
    price: 55000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-imperial-pie.png",
    materials: ["Cuero", "Alpaca", "Bronce", "Calabaza"],
    features: ["Soporte de 4 patas", "Base cincelada", "Virola premium de alpaca"],
    care: "Curar bien la calabaza. Secar patas después de lavar.",
    rating: 5.0,
    reviews: 19,
    featured: true,
    onSale: false
  },
  {
    id: "mate-seleccion-argentina",
    name: "Mate Selección Argentina",
    subtitle: "Bandera y Sol de Mayo en cuero",
    description: "Espacio para descripción personalizada. Mate tipo camionero forrado en cuero con diseño exclusivo de la bandera argentina y el Sol de Mayo en relieve.",
    price: 46000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-seleccion-argentina.jpg",
    materials: ["Cuero", "Alpaca", "Calabaza"],
    features: ["Diseño patrio exclusivo", "Costuras reforzadas", "Virola de alpaca cincelada"],
    care: "Curar con yerba húmeda. No mojar el cuero exterior.",
    rating: 5.0,
    reviews: 64,
    featured: true,
    onSale: false
  },
  {
    id: "mate-imperial-rojo-escudo",
    name: "Mate Imperial Rojo con Escudo",
    subtitle: "Cuero croco rojo y aplique de bronce",
    description: "Espacio para descripción personalizada. Mate imperial forrado en cuero rojo croco con patas de bronce y un escudo metálico dorado en la virola cincelada.",
    price: 58000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-imperial-rojo-escudo.jpg",
    materials: ["Cuero Croco", "Alpaca", "Bronce", "Calabaza"],
    features: ["Escudo de bronce aplicado", "Cuero croco rojo vibrante", "Patas de apoyo estables"],
    care: "Curar antes de usar. Limpiar aplique con paño suave.",
    rating: 4.9,
    reviews: 15,
    featured: true,
    onSale: false
  },
  {
    id: "mate-camionero-cincelado-negro",
    name: "Mate Camionero Negro Cincelado",
    subtitle: "Relieves florales y virola geométrica",
    description: "Espacio para descripción personalizada. Mate camionero con relieves tradicionales florales en el cuero negro. Virola de alpaca labrada con motivos geométricos.",
    price: 45000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-camionero-cincelado-negro.png",
    materials: ["Cuero", "Alpaca", "Calabaza"],
    features: ["Grabado floral a mano", "Virola geométrica", "Calabaza premium"],
    care: "Curar antes de usar. Secar en lugar ventilado.",
    rating: 4.8,
    reviews: 7,
    featured: false,
    onSale: false
  },
  {
    id: "mate-imperial-croco-patas",
    name: "Mate Imperial Croco Negro con Patas",
    subtitle: "Cuero textura croco y virola cincelada",
    description: "Espacio para descripción personalizada. Mate imperial forrado en cuero negro con textura croco. Base cincelada con patas de bronce y virola premium labrada.",
    price: 56000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-imperial-croco-patas.jpg",
    materials: ["Cuero Croco", "Alpaca", "Bronce", "Calabaza"],
    features: ["Cuero textura croco", "Patas de bronce de apoyo", "Virola cincelada a mano"],
    care: "Curar calabaza. Limpiar cuero con paño ligeramente húmedo.",
    rating: 4.9,
    reviews: 11,
    featured: false,
    onSale: false
  },
  {
    id: "mate-pelo-leopardo",
    name: "Mate Imperial de Pelo Leopardo",
    subtitle: "Edición exótica animal print",
    description: "Espacio para descripción personalizada. Mate imperial forrado en cuero de pelo natural con diseño animal print de leopardo. Virola de alpaca labrada a mano.",
    price: 62000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-pelo-leopardo.png",
    materials: ["Cuero de Pelo", "Alpaca", "Calabaza"],
    features: ["Pelo natural animal print", "Edición limitada exótica", "Virola cincelada premium"],
    care: "Curar calabaza. No mojar el pelo exterior, limpiar con cepillo suave.",
    rating: 5.0,
    reviews: 5,
    featured: true,
    onSale: false
  },
  {
    id: "mate-camionero-estuche-premium",
    name: "Mate Camionero Premium con Estuche",
    subtitle: "Cuero negro y estuche satinado oscuro",
    description: "Espacio para descripción personalizada. Mate camionero de cuero negro liso premium con virola cincelada de alpaca, presentado en estuche rígido negro satinado.",
    price: 48000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-camionero-estuche-premium.png",
    materials: ["Cuero", "Alpaca", "Calabaza"],
    features: ["Estuche rígido de raso negro", "Cuero liso seleccionado", "Virola cincelada"],
    care: "Curar bien antes de usar.",
    rating: 4.8,
    reviews: 14,
    featured: false,
    onSale: false
  },
  {
    id: "mate-imperial-boca-juniors",
    name: "Mate Imperial Boca Juniors",
    subtitle: "Cuero azul y escudo CABJ de bronce",
    description: "Espacio para descripción personalizada. Mate imperial de colección forrado en cuero azul Boca con patas de bronce y escudo CABJ aplicado en la virola dorada.",
    price: 59500,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-imperial-boca-juniors.png",
    materials: ["Cuero", "Alpaca", "Bronce", "Calabaza"],
    features: ["Escudo CABJ aplicado a fuego", "Cuero teñido azul Boca", "Virola dorada cincelada"],
    care: "Curar antes de usar. Limpiar exterior suavemente.",
    rating: 5.0,
    reviews: 87,
    featured: true,
    onSale: false
  },
  {
    id: "mate-madera-noble-cincelado",
    name: "Mate de Madera Noble Cincelado",
    subtitle: "Madera tallada y virola de acero",
    description: "Espacio para descripción personalizada. Mate de madera noble tallada a mano con virola de acero inoxidable cincelada con motivos tradicionales.",
    price: 33000,
    originalPrice: null,
    category: "Mates",
    categorySlug: "mates",
    image: "assets/images/products/mate-madera-noble-cincelado.png",
    materials: ["Madera", "Acero Inoxidable"],
    features: ["Madera noble aromática", "Virola de acero labrada", "No necesita curado profundo"],
    care: "Lavar con agua fría, secar bien. No dejar al sol.",
    rating: 4.7,
    reviews: 16,
    featured: false,
    onSale: false
  },
  {
    id: "bombilla-loro-bronce",
    name: "Bombilla Pico de Loro Bronce",
    subtitle: "Acero inoxidable y boquilla de bronce",
    description: "Espacio para descripción personalizada. Bombilla curva pico de loro de acero inoxidable de alta calidad, con boquilla y anillos de bronce dorado.",
    price: 18000,
    originalPrice: null,
    category: "Bombillas",
    categorySlug: "bombillas",
    image: "assets/images/products/bombilla-loro-bronce.png",
    materials: ["Acero Inoxidable", "Bronce"],
    features: ["Pico de loro anatómico", "Filtro de cuchara removible", "Detalles en bronce pulido"],
    care: "Limpiar periódicamente con cepillo interno.",
    rating: 4.8,
    reviews: 29,
    featured: false,
    onSale: false
  },
  {
    id: "bombilla-helicoidal-premium",
    name: "Bombilla Helicoidal Premium",
    subtitle: "Alpaca torsionada en espiral",
    description: "Espacio para descripción personalizada. Bombilla premium fabricada con cuerpo helicoidal torsionado en alpaca y apliques decorativos de bronce.",
    price: 24000,
    originalPrice: null,
    category: "Bombillas",
    categorySlug: "bombillas",
    image: "assets/images/products/bombilla-helicoidal-premium.png",
    materials: ["Alpaca", "Bronce"],
    features: ["Cuerpo helicoidal torsionado", "Disipador de calor", "Boquilla de bronce"],
    care: "Lavar a mano. Evitar limpiadores químicos.",
    rating: 4.9,
    reviews: 22,
    featured: true,
    onSale: false
  },
  {
    id: "bombilla-torsonada-premium",
    name: "Bombilla Torsonada Labrada",
    subtitle: "Cuerpo cincelado y apliques dorados",
    description: "Espacio para descripción personalizada. Bombilla artesanal de alpaca cincelada y torsionada, con detalles y boquilla dorada de bronce.",
    price: 23000,
    originalPrice: null,
    category: "Bombillas",
    categorySlug: "bombillas",
    image: "assets/images/products/bombilla-torsonada-premium.png",
    materials: ["Alpaca", "Bronce"],
    features: ["Cuerpo torsonado labrado", "Excelente filtrado", "Detalles de lujo"],
    care: "Hervir periódicamente con bicarbonato.",
    rating: 4.8,
    reviews: 13,
    featured: false,
    onSale: false
  },
  {
    id: "bombilla-campeon-mundo",
    name: "Bombilla Copa del Mundo",
    subtitle: "Aplique Copa y años 78, 86, 22",
    description: "Espacio para descripción personalizada. Bombilla conmemorativa de acero premium. Presenta el relieve de la Copa del Mundo en bronce y los años grabados de las conquistas mundialistas.",
    price: 26000,
    originalPrice: null,
    category: "Bombillas",
    categorySlug: "bombillas",
    image: "assets/images/products/bombilla-campeon-mundo.png",
    materials: ["Acero Inoxidable", "Bronce"],
    features: ["Relieve de Copa del Mundo", "Grabado de años '78, '86, '22", "Pico curvo cómodo"],
    care: "Limpiar a mano para proteger el relieve de bronce.",
    rating: 5.0,
    reviews: 142,
    featured: true,
    onSale: false
  },
  {
    id: "termo-deportivo-mate-acero",
    name: "Termo Deportivo con Mate de Acero",
    subtitle: "Termo Negro 1.2L + Vaso Mate Térmico",
    description: "Espacio para descripción personalizada. Combo de termo de acero inoxidable color negro mate con tapamate de doble pared térmica de acero inoxidable.",
    price: 45000,
    originalPrice: null,
    category: "Termos",
    categorySlug: "termos",
    image: "assets/images/products/termo-deportivo-mate-acero.png",
    materials: ["Acero Inoxidable"],
    features: ["Doble pared aislante de vacío", "Conserva calor por 24hs", "Incluye mate térmico de acero"],
    care: "Lavar a mano. Secar destapado.",
    rating: 4.9,
    reviews: 35,
    featured: true,
    onSale: false
  },
  {
    id: "termo-grabado-argentina",
    name: "Termo Grabado Láser Argentina",
    subtitle: "Ilustraciones criollas y escudo nacional",
    description: "Espacio para descripción personalizada. Termo de acero inoxidable grabado a láser con ilustraciones autóctonas argentinas y el Escudo Nacional en el centro.",
    price: 43000,
    originalPrice: null,
    category: "Termos",
    categorySlug: "termos",
    image: "assets/images/products/termo-grabado-argentina.jpg",
    materials: ["Acero Inoxidable"],
    features: ["Grabado láser permanente", "Media manija ergonómica", "Capacidad 1 Litro"],
    care: "Lavar exterior únicamente con esponja suave.",
    rating: 4.9,
    reviews: 58,
    featured: true,
    onSale: false
  },
  {
    id: "canasta-matera-rigida",
    name: "Canasta Matera Rígida de Cuero",
    subtitle: "Chocolate con costuras beige a mano",
    description: "Espacio para descripción personalizada. Matera rígida de cuero vacuno color chocolate. Costuras cruzadas a mano en hilo beige y manija ultra resistente.",
    price: 36000,
    originalPrice: null,
    category: "Canastas",
    categorySlug: "canastas",
    image: "assets/images/products/canasta-matera-rigida.png",
    materials: ["Cuero Vacuno"],
    features: ["Costuras reforzadas beige", "Divisor interno estructurado", "Asa reforzada para colgar"],
    care: "Limpiar cuero con lustramuebles o crema hidratante.",
    rating: 4.9,
    reviews: 21,
    featured: false,
    onSale: false
  },
  {
    id: "tabla-boca-juniors",
    name: "Tabla de Asado Boca Juniors",
    subtitle: "Madera de pino con canaletas y escudo",
    description: "Espacio para descripción personalizada. Tabla de asado/picadas de madera de pino de alta densidad. Cuenta con canaleta para jugos y escudo de Boca Juniors grabado a láser.",
    price: 25000,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/tabla-boca-juniors.png",
    materials: ["Madera"],
    features: ["Grabado láser Boca Juniors", "Madera curada de alta resistencia", "Canaletas anti-derrame"],
    care: "Lavar a mano, secar de inmediato. Curar con aceite vegetal ocasionalmente.",
    rating: 4.9,
    reviews: 94,
    featured: true,
    onSale: false
  },
  {
    id: "tabla-river-plate",
    name: "Tabla de Asado River Plate",
    subtitle: "Madera de pino con canaletas y escudo CARP",
    description: "Espacio para descripción personalizada. Tabla de asado/picadas de madera noble de pino de alta densidad con canaletas para jugos y el escudo de River Plate grabado a láser.",
    price: 25000,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/tabla-river-plate.png",
    materials: ["Madera"],
    features: ["Grabado láser River Plate", "Madera curada de alta calidad", "Canaletas para jugos"],
    care: "Lavar y secar de inmediato. Hidratar con aceite vegetal.",
    rating: 4.9,
    reviews: 82,
    featured: true,
    onSale: false
  },
  {
    id: "kit-tapa-mate",
    name: "Kit Tapa Mate y Tapa Bombilla",
    subtitle: "Silicona flexible anti-derrames",
    description: "Espacio para descripción personalizada. Kit de tapamate y tapabombilla de silicona elástica de alta densidad. Ideal para transportar el mate preparado sin derramar yerba ni agua.",
    price: 7500,
    originalPrice: null,
    category: "Accesorios",
    categorySlug: "accesorios",
    image: "assets/images/products/kit-tapa-mate.png",
    materials: ["Silicona"],
    features: ["Silicona grado alimenticio", "Ajuste universal elástico", "Evita derrames al viajar"],
    care: "Lavar con agua jabonosa.",
    rating: 4.6,
    reviews: 33,
    featured: false,
    onSale: false
  },
  {
    id: "matera-cuero-box",
    name: "Matera Box de Cuero con Cerradura",
    subtitle: "Cerradura vintage y cuero grabado",
    description: "Espacio para descripción personalizada. Estuche portatermo rígido tipo box elaborado en cuero vacuno negro con cerradura metálica de bronce estilo vintage.",
    price: 39000,
    originalPrice: null,
    category: "Canastas",
    categorySlug: "canastas",
    image: "assets/images/products/matera-cuero-box.png",
    materials: ["Cuero Vacuno", "Bronce"],
    features: ["Cerradura de bronce vintage", "Estructura interna rígida", "Cuero grabado lateral"],
    care: "Limpiar exterior con paño húmedo.",
    rating: 4.9,
    reviews: 18,
    featured: true,
    onSale: false
  }
];

// Helper to filter/sort
const getProductsByCategory = (slug) => PRODUCTS.filter(p => p.categorySlug === slug);
const getProductById = (id) => PRODUCTS.find(p => p.id === id);
const getFeaturedProducts = () => PRODUCTS.filter(p => p.featured);

const getProductsByMaterial = (material) => PRODUCTS.filter(p => 
  p.materials.some(m => m.toLowerCase().includes(material.toLowerCase()))
);

const getProductsByType = (type) => PRODUCTS.filter(p => {
  const t = type.toLowerCase();
  return p.name.toLowerCase().includes(t) || 
         p.subtitle.toLowerCase().includes(t) || 
         (p.id && p.id.includes(t));
});

const sortProducts = (products, type) => {
  switch (type) {
    case 'price-asc': return [...products].sort((a, b) => a.price - b.price);
    case 'price-desc': return [...products].sort((a, b) => b.price - a.price);
    case 'rating': return [...products].sort((a, b) => b.rating - a.rating);
    case 'featured': default: return [...products].sort((a, b) => (b.featured ? 1 : -1));
  }
};
